branch-defaults:
  master:
    environment: node-express-crud-env
    group_suffix: null
global:
  application_name: crud-web-application
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
